AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy VPCEndpoints(ComputeVPC)
#----------------------------------------------
Resources:
  #------Security Group
  VpceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SSMTestVPC-VpceSG
      GroupDescription: "Allow TLS access from the same VPC"
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      SecurityGroupIngress: 
        - 
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
  #------VPC Endpoint
  SsmEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet1Id
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet2Id
      SecurityGroupIds: 
        - !Ref VpceSG
      PolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" 
            Action: "ssm:*"
            Resource: "*"
  SsmMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet1Id
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet2Id
      SecurityGroupIds: 
        - !Ref VpceSG
      PolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" 
            Action: "ssmmessages:*"
            Resource: "*"
  Ec2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet1Id
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet2Id
      SecurityGroupIds: 
        - !Ref VpceSG
      PolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" 
            Action: "ec2messages:*"
            Resource: "*"

  Logs:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet1Id
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet2Id
      SecurityGroupIds: 
        - !Ref VpceSG
      PolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"  
            Action: "logs:*"
            Resource: "*"
  s3gw:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet1RouteTableId
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet2RouteTableId
      PolicyDocument:
        Statement:
          - 
            Sid: AllowSsmAgentPackageStorageBucket
            Effect: Allow
            Principal: "*"
            Action: "s3:*"
            Resource:
              # SSM Agentインストール/更新用(インストールパッケージ格納先)
              - !Sub "arn:aws:s3:::amazon-ssm-${AWS::Region}/*"
          - 
            Sid: AllowOwnedBuckets
            Effect: Allow
            Principal: "*"
            Action: "s3:*"
            Resource: "*"
            Condition:
              StringEquals:
                s3:ResourceAccount: !Sub "${AWS::AccountId}"
  kms:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: 
        Fn::ImportValue: SSMTestVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.kms
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet1Id
        - Fn::ImportValue: SSMTestVPC-PrivateSubnet2Id
      SecurityGroupIds: 
        - !Ref VpceSG
      PolicyDocument:
        Statement:
          - 
            Effect: Allow
            Principal: "*"
            Action: "kms:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/*"